updates showoff version to 0.19.6
NETWAYS/foreman-training pull request #14
Opened 2019-03-18 12:33 UTC by tbauriedel

I´ve updated showoff version to 0.19.6

2019-03-19 15:26 UTC, dnsmichi commented
Readme says 0.20.0 instead?

https://github.com/NETWAYS/foreman-training/pull/14/commits/4cfa8240cdd53d0063cba1b45f2f961972c95d51#diff-04c6e90faac2675aa89e2176d2eec7d8R29

2019-03-19 15:32 UTC, dgoetz commented
There are also some more small issues I have seen on the first look, I will review on Thursday.

2019-03-21 12:08 UTC, dgoetz requested changes
See my inline comments for smaller changes required.
Furthermore the last slides from demo to contributing should be vertically and horizontally be centered and tables should be better layout-ed in presentation and print.
Can you also add the new wizard script using prepared docker images to the README?
The solutions for "Configure Graphical Integration" look strange, can you have a look into this?
After all the changes please regenerate the static html!

2019-03-21 12:08 UTC, dgoetz commented on README.md
> +To run the presentation you will need [showoff 0.20.0](https://rubygems.org/gems/showoff/versions/0.20.0).
Should be 0.19.6

2019-03-21 12:08 UTC, dgoetz commented on advanced/03_api.md
> +~~~PAGEBREAK~~~~~PAGEBREAK~~~~
Should be only ~~~PAGEBREAK~~~

2019-03-21 12:08 UTC, dgoetz commented on advanced/01_web.md
> +<br>
No html formating if not really necessary

2019-03-21 12:08 UTC, dgoetz commented on advanced/04_cli.md
> +<br>A list of plugins is provided by the Github page of the framework: https://github.com/theforeman/hammer-cli
No html formating if not really necessary

2019-03-21 12:08 UTC, dgoetz commented on advanced/06_troubleshooting.md
> +~~~PAGEBREAK~~~
Is it possible to have at least the first paragraph on the page?

2019-03-21 12:08 UTC, dgoetz commented on architecture/00_overview.md
> +<p>Foreman was originally writen by Paul Kelly and Ohad Levy and initially released on 10 September 2009.<br>
No html formating if not really necessary

2019-03-21 12:08 UTC, dgoetz commented on architecture/01_foreman.md
> +~~~PAGEBREAK~~~
Please add the horizontal line `****` before it.

2019-03-21 12:08 UTC, dgoetz commented on architecture/02_smart_proxy.md
> +~~~PAGEBREAK~~~
Is it possible to have the first paragraph on the page?

2019-03-21 12:08 UTC, dgoetz commented on architecture/03_compute_resource.md
> -****
Please do not remove the horizontal line.

2019-03-21 12:08 UTC, dgoetz commented on architecture/01_foreman.md
> +<img src="./_images/foreman_loginscreen.png" style="max-width3200px; max-height: 200px; width: 300px; height: 120px; margin: 1px; margin-right: 100px" alt="Foreman Loginscreen"/>
`max-width3200px; ` is not valid.

2019-03-21 12:08 UTC, dgoetz commented on configmanagement/02_puppet.md
> +#Puppet
If it needs to be spilt up, slide name should be "Puppet Workflow" and the bullet point "Workflow" could be eliminated and the others moved one level up. Also split up the handouts matching the slides.
Another way to handle it would be to split up the slide only in the presentation.

2019-03-21 12:08 UTC, dgoetz commented on configmanagement/02_puppet.md
> +!SLIDE smbullets small
Please split up this slide only in presentation.

2019-03-21 12:08 UTC, dgoetz commented on global/Pre/Title/01_Title.md
> +<div class="title-subtitle"><p>created by NETWAYS GmbH</p></div>
Can you increase the subtitle font to be at least as big as the author font?

2019-03-21 12:08 UTC, dgoetz commented on installation/03_scenarios.md
> +<div style="text-align:center"><img src="./_images/installation_additional-masters.png" style="float: center; margin-left: 50px; width: 616px; height: 393px;" alt="Installation Additional Puppet Mast
Can you adjust width also, so it keeps format?

2019-03-21 12:08 UTC, dgoetz commented on installation/03_scenarios.md
> +<img src="./_images/installation_additional-masters.png" style="width: 450px; height: 393px;" alt="Installation Additional Puppet Masters">
Can you adjust width also, so it keeps format?

2019-03-21 12:08 UTC, dgoetz commented on installation/03_scenarios.md
> +<div style="text-align:center"><img src="./_images/installation_separate-masters.png" style="float: center; margin-left: 50px; width: 616px; height: 446px;" alt="Installation Separate Puppet Masters"
Can you adjust width also, so it keeps format?

2019-03-21 12:08 UTC, dgoetz commented on installation/03_scenarios.md
> +<p>The Foreman installer allows to add PuppetDB as reporting target and storeconfigs backend
No html formating if not necessary.

2019-03-21 12:08 UTC, dgoetz commented on plugins/01_default_hostgroup.md
> +<p><br></p>
Is this required?

2019-03-21 12:08 UTC, dgoetz commented on plugins/02_templates.md
> -****
Please do not remove the horizontal line

2019-03-21 12:08 UTC, dgoetz commented on plugins/09_cockpit.md
Please do not remove the horizontal line

2019-03-21 12:08 UTC, dgoetz commented on plugins/11_expire_hosts.md
> -****
Please do not remove.

2019-03-21 12:08 UTC, dgoetz commented on plugins/12_monitoring.md
> +~~~PAGEBREAK~~~~~PAGEBREAK~~~~
Should be ~~~PAGEBREAK~~~

2019-03-21 12:08 UTC, dgoetz commented on provisioning/03_pxe.md
> +<div style="text-align:center"><img src="./_images/pxe.png" style="float: center; margin-left: 125px; width: 760px; height: 340px;" alt="Provisioning PXE"></div>
Image is not fitting on print.

2019-03-21 12:08 UTC, dgoetz commented on provisioning/04_compute_resource.md
> +<div style="text-align: center"><img src="./_images/compute_resource.png" style="float: center; margin-left: 110px; width: 795px; height: 445px;" alt="Provisioning Compute resource libvirt"></div>
Image is not fitting on print.

2019-03-21 12:08 UTC, dgoetz commented on provisioning/04_compute_resource.md
> +<p><br></p>
Is this required?

2019-03-21 12:08 UTC, dgoetz commented on provisioning/05_discovery.md
> -****
Please do not remove

2019-03-21 12:08 UTC, dgoetz commented on provisioning/06_bootdisk.md
> -****
Please do not remove.

2019-03-21 12:08 UTC, dgoetz commented on training/01_training.md
> +<h3>This training course will introduce the architectual concepts of Foreman, will cover installation, usage and administration.
No html formating if not necessary. If necessary, please do not abuse headlines.

2019-03-21 12:08 UTC, dgoetz commented on training/01_training.md
> -****
Please do not remove

2019-03-21 12:08 UTC, dgoetz commented on training/03_environment.md
> +<div style="text-align: center"><img src="./_images/environment.png" style="float: center; margin-left: 115px; width: 794px; height: 428px;" alt="Training Environment"></div>
Image is not fitting in print.

2019-03-21 12:08 UTC, dgoetz commented on training/03_environment.md
> +<p>The laptop provided for the training is running CentOS 7 with Gnome 3 in Fallback mode.
No html formating if not nessary.

2019-03-21 12:08 UTC, dgoetz commented on usermanagement/06_sshkeys.md
> +<img src="./_images/foreman_usersshkey.png" style="float: right, max-width:200px; max-height: 250px; width: auto; height: auto; margin-top: 90px; margin-right: 151px" alt="Foreman User SSH Keys"/>
Please resize the image on print.

2019-03-21 12:08 UTC, dgoetz commented on usermanagement/05_email.md
> +<img src="./_images/foreman_email.png" style="float: right, max-width:200px; max-height: 250px; width: auto; height: auto; margin-top: 50px; margin-right: 265px" alt="Foreman Email"/>
Please resize the image on print.

2019-08-13 12:43 UTC, dgoetz commented
I resolved all solved inline comments, so not resolved ones are still open.
From the additional list is still open:
- Furthermore the last slides from demo to contributing should be vertically and horizontally be centered and tables should be better layout-ed in presentation and print.
- Can you also add the new wizard script using prepared docker images to the README?
- After all the changes please regenerate the static html!

2019-09-05 11:36 UTC, dgoetz requested changes
Still some inline comments.
Furthermore only the one table looks ok, the other one with the ports looks different.
The split of the slides in the Puppet section is still wrong and the size of the image of the ssh_keys in the print.
The README is not correct. You install showoff and use `showoff serve` or use docker and the wizard script.

2019-09-05 11:36 UTC, dgoetz commented on architecture/01_foreman.md
> +<img src="./_images/foreman_loginscreen.png" style="max-width320px; max-height: 200px; width: 300px; height: 120px; margin: 1px; margin-right: 100px" alt="Foreman Loginscreen"/>
max-width320px is not valid

2019-09-05 11:36 UTC, dgoetz commented on installation/03_scenarios.md
> +to the Puppet Masters. It does not setup PuppetDB server!<br/>
Please use newline instead of <br/> (Markdown instaed of HTML).

2019-11-14 14:36 UTC, dgoetz approved these changes
I pushed some of the missing changes and will merge it now. If something is still missing we can do this in a separate change.

2019-11-14 14:36 UTC, merged